### ISSUE TITLE
get_positions() error

### ISSUE THREAD

**Issue by CDittmeier** [JestonBlu/RobinHood#46]
I am not able to see currently held positions. I'm curious if the issue stems from the option I own on my account. 

Error:

Error in data.frame(simple_name = instrument$simple_name, symbol = instrument$symbol) : 
  arguments imply differing number of rows: 0, 1

Code:
```library(RobinHood)
username <- rstudioapi::askForPassword("RobinHood username")
password <- rstudioapi::askForPassword("RobinHood password")


RH <- RobinHood(username = username, password = password)

get_positions(RH, limit_output= TRUE)

**Comment by JestonBlu** [comment]
When you call RH, do you you have keys populated? This would confirm that your RobinHood connection was successful.  

Do you currently have positions or are you expecting it to return empty?

I have not tested RH with the askForPassword function. I will do that tonight.

**Comment by CDittmeier** [comment]
Yeah the login works fine and I'm having no issues with other functions - just get_positions(). For example get_order_history(RH) works here. I did notice that the order history doesn't include any stock options transactions I've done - so I'm wondering if having stock options in my portfolio causes get_positions to fail.

**Comment by CDittmeier** [comment]
<img width="282" alt="Screen Shot 2019-03-27 at 1 51 59 PM" src="https://user-images.githubusercontent.com/24812731/55100177-9d3fd200-5097-11e9-84f4-0687fd11d1e7.png">

Here is what I'm expecting to see for reference

**Comment by JestonBlu** [comment]
Interesting, i think options might be a separate API call. I will look in to this further tonight and let you know what I find. Thanks for the feedback.

**Comment by CDittmeier** [comment]
Thanks. I'm enjoying the package so far.

**Comment by JestonBlu** [comment]
I have never used options before. I just changed my account to allow options trading which I will test tomorrow.  

The current CRAN release filters out any quantities that are = 0 so that might be why you are not getting results. There also appears to be a bug where `get_positions` will throw an error if you don't have any current positions. I have added warning messages that will tell you if you have no positions.

There are a few columns that return in `get_positions(RH, limit = FALSE)` that appear to be related to options activity. I have added a new parameter, `options = TRUE` (FALSE is default) which will look to see if any of these quantity positions are greater than 0. 

```r
get_positions(RH, limit = FALSE, options = TRUE)
```
I have pushed these changes to github so if you would like to test it out replace the CRAN package with the github version.

I will hopefully be able to validate these changes and and make any needed adjustments tomorrow.

**Comment by CDittmeier** [comment]
I went ahead and gave it a shot and it returned "You have no current positions or options" despite having both (although I think options are technically positions so that might be redundant). I'll check back in once you've had time to test it. 

Any plans to add get_historicals in the robinhood.Portfolio class, and maybe get_notifications to grab deposits/withdrawals? Anything to work back to historical account balance would be useful. 

Thanks!

**Comment by JestonBlu** [comment]
Yeah, i saw that this morning. I have pushed a fix so that stock ownership positions return correctly https://github.com/JestonBlu/RobinHood/commit/cf9cc4ca0d01db9321efe793786e7a00d1fc72d5. 

So far I have been unable to find purchased options contracts in the API. Since the API is not public I have to rely on work others have down to extract that info. In my digging I have found out how to pull in the options market data so I am adding that to the enhancement list.

I wonder if options will only show up in the get_positions api call if the options contract is exercised. I will keep an eye on that and continue researching it. Either way I think I will probably create a separate function to extract options contracts.

I have been getting historical data from another package Im developing, but I think you are right that I should include it as a feature in RobinHood. Here is a reference to the other package which isn't as far along as this one https://github.com/JestonBlu/IEXTrader. 

I have created some new issues to address some of your ideas individually.
- [ ] Add feature to retrieve options market data #47
- [ ] Add feature to retrieve purchased options contracts #48
- [ ] Add `get_historicals` for historical price data #49
- [ ] Research adding feature for interacting with ACH transfers #50
- [ ] Research `get_portfolio` #51
- [ ] Research feature for calculating historical account balance #52

If you can validate that `get_positions` is now returning the stocks you own shares in then I think we can close this issue and I can work on the new features in the respective issue thread.

Thanks for all the feedback, its cool to see someone using my first R package!

**Comment by CDittmeier** [comment]
Thanks for your work on this. I am still receiving the same error. I went ahead and included the console output below (I still had my password and username stored in the environment so that code is not included).

```
> library(tidyverse)
> library(RobinHood)

> RH <- RobinHood(username = username, password = password)
> orderHistory <- get_order_history(RH)
> orderHistory
            created_at symbol side  price quantity fees     state average_price
1  2019-03-27 14:45:37   CRBP  buy   7.00        5 0.00    filled        6.9382
2  2019-02-26 14:52:14   CPRX sell     NA       15 0.02    filled        3.0619
3  2019-02-22 16:02:48   KODK sell     NA        9 0.02    filled        3.1123
4  2018-11-29 14:57:03   CPRX sell   3.25       15 0.00 cancelled            NA
5  2018-11-29 14:55:24   CPRX  buy   2.96       15 0.00    filled        2.8300
6  2018-11-28 20:00:25   GPRO sell     NA        1 0.02    filled        5.3715
7  2018-11-28 18:57:41    AUY sell     NA        3 0.02    filled        2.1402
8  2018-11-28 18:52:02    DNR sell     NA        1 0.02    filled        2.3701
9  2018-11-17 17:46:58   ADBE  buy 250.64        1 0.00    filled      237.5000
10 2018-11-07 20:26:28     ZG  buy  31.76        1 0.00    filled       30.2500
11 2018-11-06 18:31:39   TMFC sell     NA        1 0.02    filled       20.5505
12 2018-11-02 19:46:31   TMFC sell  20.93        1 0.00 cancelled            NA
13 2018-11-02 17:35:00   KODK  buy   2.82        4 0.00    filled        2.7000
14 2018-11-02 17:31:53   ESGV  buy  48.82        1 0.00    filled       46.5390
15 2018-11-01 19:18:28   SPOT  buy 147.44        1 0.00    filled      140.4876
16 2018-10-26 15:45:37   KODK  buy   2.49        1 0.00    filled        2.3899
17 2018-10-26 14:17:33   GPRO  buy   6.14        1 0.00    filled        5.8585
18 2018-10-26 14:15:08   SIRI sell     NA        1 0.02    filled        5.6803
19 2018-10-25 19:56:25    AUY  buy   2.58        3 0.00    filled        2.4599
20 2018-10-25 19:54:09   KODK  buy   2.61        4 0.00    filled        2.4899
21 2018-10-21 19:58:22   TMFC  buy  21.82        1 0.00    filled       20.9300
22 2018-10-21 19:54:44   SBUX  buy  61.34        1 0.00    filled       58.9300
     type   trigger time_in_force          updated_at
1  market immediate           gfd 2019-03-27 14:45:38
2  market immediate           gfd 2019-02-26 14:52:15
3  market immediate           gfd 2019-02-22 16:02:49
4   limit immediate           gtc 2018-11-30 15:46:32
5  market immediate           gfd 2018-11-29 14:55:25
6  market immediate           gfd 2018-11-28 20:00:26
7  market immediate           gfd 2018-11-28 18:57:42
8  market immediate           gfd 2018-11-28 18:52:03
9  market immediate           gfd 2018-11-19 14:31:28
10 market immediate           gfd 2018-11-07 20:26:29
11 market immediate           gfd 2018-11-06 18:31:40
12  limit immediate           gtc 2018-11-06 18:31:26
13 market immediate           gfd 2018-11-02 17:35:00
14 market immediate           gfd 2018-11-02 17:31:54
15 market immediate           gfd 2018-11-01 19:18:29
16 market immediate           gfd 2018-10-26 15:45:38
17 market immediate           gfd 2018-10-26 14:17:33
18 market immediate           gfd 2018-10-26 14:15:09
19 market immediate           gfd 2018-10-25 19:56:25
20 market immediate           gfd 2018-10-25 19:54:09
21 market immediate           gfd 2018-10-22 13:30:00
22 market immediate           gfd 2018-10-22 13:30:10

> get_positions(RH, limit_output= FALSE)
Error in data.frame(simple_name = instrument$simple_name, symbol = instrument$symbol) : 
  arguments imply differing number of rows: 0, 1

**Comment by CDittmeier** [comment]
Thanks for your work on this. I'm still getting the same error after reinstalling the package. I've included the console output below:

```
> library(RobinHood)
> library(tidyverse)
> username <- rstudioapi::askForPassword("RobinHood username")
> password <- rstudioapi::askForPassword("RobinHood password")
> RH <- RobinHood(username = username, password = password)
> get_positions(RH, limit_output= FALSE)
Error in data.frame(simple_name = instrument$simple_name, symbol = instrument$symbol) : 
  arguments imply differing number of rows: 0, 1
> orderHistory <- get_order_history(RH)
> orderHistory
            created_at symbol side  price quantity fees     state average_price
1  2019-03-27 14:45:37   CRBP  buy   7.00        5 0.00    filled        6.9382
2  2019-02-26 14:52:14   CPRX sell     NA       15 0.02    filled        3.0619
3  2019-02-22 16:02:48   KODK sell     NA        9 0.02    filled        3.1123
4  2018-11-29 14:57:03   CPRX sell   3.25       15 0.00 cancelled            NA
5  2018-11-29 14:55:24   CPRX  buy   2.96       15 0.00    filled        2.8300
6  2018-11-28 20:00:25   GPRO sell     NA        1 0.02    filled        5.3715
7  2018-11-28 18:57:41    AUY sell     NA        3 0.02    filled        2.1402
8  2018-11-28 18:52:02    DNR sell     NA        1 0.02    filled        2.3701
9  2018-11-17 17:46:58   ADBE  buy 250.64        1 0.00    filled      237.5000
10 2018-11-07 20:26:28     ZG  buy  31.76        1 0.00    filled       30.2500
11 2018-11-06 18:31:39   TMFC sell     NA        1 0.02    filled       20.5505
12 2018-11-02 19:46:31   TMFC sell  20.93        1 0.00 cancelled            NA
13 2018-11-02 17:35:00   KODK  buy   2.82        4 0.00    filled        2.7000
14 2018-11-02 17:31:53   ESGV  buy  48.82        1 0.00    filled       46.5390
15 2018-11-01 19:18:28   SPOT  buy 147.44        1 0.00    filled      140.4876
16 2018-10-26 15:45:37   KODK  buy   2.49        1 0.00    filled        2.3899
17 2018-10-26 14:17:33   GPRO  buy   6.14        1 0.00    filled        5.8585
18 2018-10-26 14:15:08   SIRI sell     NA        1 0.02    filled        5.6803
19 2018-10-25 19:56:25    AUY  buy   2.58        3 0.00    filled        2.4599
20 2018-10-25 19:54:09   KODK  buy   2.61        4 0.00    filled        2.4899
21 2018-10-21 19:58:22   TMFC  buy  21.82        1 0.00    filled       20.9300
22 2018-10-21 19:54:44   SBUX  buy  61.34        1 0.00    filled       58.9300
     type   trigger time_in_force          updated_at
1  market immediate           gfd 2019-03-27 14:45:38
2  market immediate           gfd 2019-02-26 14:52:15
3  market immediate           gfd 2019-02-22 16:02:49
4   limit immediate           gtc 2018-11-30 15:46:32
5  market immediate           gfd 2018-11-29 14:55:25
6  market immediate           gfd 2018-11-28 20:00:26
7  market immediate           gfd 2018-11-28 18:57:42
8  market immediate           gfd 2018-11-28 18:52:03
9  market immediate           gfd 2018-11-19 14:31:28
10 market immediate           gfd 2018-11-07 20:26:29
11 market immediate           gfd 2018-11-06 18:31:40
12  limit immediate           gtc 2018-11-06 18:31:26
13 market immediate           gfd 2018-11-02 17:35:00
14 market immediate           gfd 2018-11-02 17:31:54
15 market immediate           gfd 2018-11-01 19:18:29
16 market immediate           gfd 2018-10-26 15:45:38
17 market immediate           gfd 2018-10-26 14:17:33
18 market immediate           gfd 2018-10-26 14:15:09
19 market immediate           gfd 2018-10-25 19:56:25
20 market immediate           gfd 2018-10-25 19:54:09
21 market immediate           gfd 2018-10-22 13:30:00
22 market immediate           gfd 2018-10-22 13:30:10

**Comment by JestonBlu** [comment]
Strange, I'm not able to duplicate your results. I have tried testing it a few different ways. Both with and without any shares owned in my account. Can you confirm that you are on the GitHub version and that you have restarted R since reinstalling?

I do see the error in the CRAN version when you own no shares, but that has been fixed in the current development version.

```r
library(RobinHood)
library(magrittr)

username = "username"
password = "password"

RH = RobinHood(username, password)
```

#### Development version 1.0.2 on Github

```r
get_positions(RH, limit_output = FALSE) %>% str

'data.frame':	1 obs. of  18 variables:
 $ symbol                            : Factor w/ 1 level "AMRS": 1
 $ simple_name                       : Factor w/ 1 level "Amyris": 1
 $ quantity                          : num 1
 $ average_buy_price                 : num 2.2
 $ last_trade_price                  : num 2.19
 $ cost                              : num 2.2
 $ current_value                     : num 2.19
 $ shares_held_for_stock_grants      : num 0
 $ shares_held_for_options_events    : num 0
 $ shares_held_for_options_collateral: num 0
 $ shares_held_for_buys              : num 0
 $ shares_held_for_sells             : num 0
 $ shares_pending_from_options_events: num 0
 $ pending_average_buy_price         : num 2.2
 $ intraday_average_buy_price        : num 0
 $ intraday_quantity                 : num 0
 $ created_at                        : POSIXct, format: "2019-02-11 04:43:58"
 $ updated_at                        : POSIXct, format: "2019-03-28 14:19:45"
```
#### Development Version with no shares

```r
> get_positions(RH)
Error in get_positions(RH) : You have no current positions
```

#### CRAN Version 1.0.1 with shares
```r
> get_positions(RH, limit_output = FALSE) %>% str

'data.frame':	1 obs. of  18 variables:
 $ symbol                            : Factor w/ 1 level "AMRS": 1
 $ simple_name                       : Factor w/ 1 level "Amyris": 1
 $ quantity                          : num 1
 $ average_buy_price                 : num 2.2
 $ last_trade_price                  : num 2.19
 $ cost                              : num 2.2
 $ current_value                     : num 2.19
 $ shares_held_for_stock_grants      : num 0
 $ shares_held_for_options_events    : num 0
 $ shares_held_for_options_collateral: num 0
 $ shares_held_for_buys              : num 0
 $ shares_held_for_sells             : num 0
 $ shares_pending_from_options_events: num 0
 $ pending_average_buy_price         : num 2.2
 $ intraday_average_buy_price        : num 0
 $ intraday_quantity                 : num 0
 $ created_at                        : POSIXct, format: "2019-02-11 04:43:58"
 $ updated_at                        : POSIXct, format: "2019-03-28 14:19:45"
```

#### CRAN Version with no shares
```r
> get_positions(RH)

Error in curl_fetch_memory(., url = instrument_id) : 
  Could not resolve host: NA
```

**Comment by CDittmeier** [comment]
I went down the rabbit hole and found out what was causing the issue. I have a share of Vanguard ESG U.S. Stock ETF  - $ESGV that does not have a simple name. Because it returned NULL for simple name in the get_positions function, it threw off the code below when it returned different lengths for names and symbols. I was able to fix this by subbing the simple_name field for name. I'd consider adding a check to see if simple name is null for the instrument and returning the name if that is the case. 

```for (i in 1:length(instrument_id)) {
    instrument <- api_instruments(RH, instrument_url = instrument_id[i])
    
    x <- data.frame(simple_name = instrument$symple_name, symbol = instrument$symbol)
    
    instruments <- rbind(instruments, x)
  }```

**Comment by JestonBlu** [comment]
Awesome, thanks for digging into it. I will patch and push your fix later tonight. On a side note I have found the api calls for option positions and order history and I'm currently working on adding those new functions. I also recently added get_portfolios and get_historicals... One thing I have been thinking about regarding your earlier comment... what do you mean by portfolio class?

**Comment by CDittmeier** [comment]
I was referencing a vague line [here](https://github.com/sanko/Robinhood/blob/master/Unsorted.md) where it mentions: "Get Portfolio Historicals	GET /portfolios/historicals/$accountNumber?span=...&interval=..." Not sure if I understand what that is describing. Not sure what I meant by class. I'll check out get_portfolios and get_historicals. Thanks!

**Comment by JestonBlu** [comment]
I have implemented your fix (7a26e0ecbb140ea6a59f2bc95485b592faff7726). Would you mind checking to see if it works for you? I tested the reference above and was able to pull historical portfolio data as well so I have also incorporated `interval` and `span` as new parameters in `get_portfolio()`

```r
get_portfolios(RH, interval = "day", span = "3month")
```

**Comment by CDittmeier** [comment]
Looks like that worked. Thanks! Also appreciate the get_portfolio() function.
